
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # O la rama que uses como principal (ej. master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Asegúrate que coincida con tu entorno de desarrollo/package.json

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # GITHUB_TOKEN se provee automáticamente
          firebaseServiceAccount: '' # Dejar vacío si se usa firebaseToken
          firebaseToken: '${{ secrets.FIREBASE_TOKEN }}'
          projectId: 'santa-brisa-crm' # ID de Proyecto Firebase actualizado
          channelId: live # Despliega al canal "live" (producción)
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels # Necesario para usar channels si se desea en el futuro
